language: python
python:
  - "2.7"
branches:
  only:
    - master
sudo: required
script:
  - sudo python setup.py install
  - pwd
  - cd flaskr/
  - pwd
  - ls
  - cp gtfshandler.py tests/gtfshandler.py
  - python tests/calendar_tests.py
